# Use an official Node.js image as the base image
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json from the React project folder (booksui)
COPY booksui/package*.json ./

# Install dependencies using npm
RUN npm install

# Set the working directory to booksui
WORKDIR /app/booksui

# Copy the rest of the React application code from the booksui folder
COPY booksui/ .

# Build the React app for production
RUN npm run build

# Use an nginx image to serve the static files
FROM nginx:alpine
COPY --from=0 /app/booksui/build /usr/share/nginx/html

# Expose the port nginx will use
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
