# Generated by Django 5.0.1 on 2024-01-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_customer_budget_alter_customer_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='books',
        ),
        migrations.AddField(
            model_name='customer',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='customer_books', to='app_store.book'),
        ),
    ]
