# Generated by Django 5.0.1 on 2024-08-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0003_remove_customer_books_customer_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_url',
            field=models.URLField(default='https://5.imimg.com/data5/SELLER/Default/2021/1/OK/HV/TZ/119567041/ikigai-500x500.jpeg'),
        ),
    ]
