# Generated by Django 5.0.1 on 2024-08-26 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0004_book_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Bought',
        ),
    ]
